# When accessing this in the code you'll work with it as a dict.
# ENV variables will be replaced with their values. This is done with the envyaml package that is in the code template `load_config`.
# By convention all variables for the project should have the BIFROST_BRIDGE_* prefix.
# e.g
# name: ${BIFROST_BRIDGE_NAME}
example:
    input:
        name: ${BIFROST_BRIDGE_USER_INPUT_NAME}
        alternative_name: Lee

