{% set name = "bifrost_bridge" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 83a04d609e3fc340365dcc519f7ae1a9b6820a0a63e1d20cd6ea67a24d870358

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - python >=3.11,<3.15
    - pip
    - hatchling
  run:
    - python >=3.11,<3.15
    - pandas >=3.0.3,<4
    - pyyaml >=6.0.3,<7

test:
  imports:
    - bifrost_bridge
  commands:
    - bridge_mlst --help
    - bridge_fastp --help
    - bridge_quast --help
    - bridge_plasmidfinder --help
    - bridge_amrfinderplus --help
    - bridge_bracken --help
    - bridge_pmlst --help
    - bridge_rmlst --help
    - bridge_shovill --help
    - bridge_ssiamb --help
    - bridge_qc --help

about:
  home: https://github.com/ssi-dk/bifrost_bridge
  summary: Normalize bioinformatics QC tool outputs into TSV summaries
  description: |
    bifrost_bridge converts outputs from multiple bioinformatics QC tools into
    normalized TSV files and can combine them into a single QC table.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ssi-dk/bifrost_bridge

extra:
  recipe-maintainers:
    - PovilasMat
