# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bifrost_bridge',
                'doc_host': 'https://$GIT_USER_NAME.github.io',
                'git_url': 'https://github.com/$GIT_USER_NAME/bifrost_bridge',
                'lib_path': 'bifrost_bridge'},
  'syms': { 'bifrost_bridge.core': { 'bifrost_bridge.core.cli': ('core.html#cli', 'bifrost_bridge/core.py'),
                                     'bifrost_bridge.core.get_config': ('core.html#get_config', 'bifrost_bridge/core.py'),
                                     'bifrost_bridge.core.get_samplesheet': ('core.html#get_samplesheet', 'bifrost_bridge/core.py'),
                                     'bifrost_bridge.core.hello_world': ('core.html#hello_world', 'bifrost_bridge/core.py'),
                                     'bifrost_bridge.core.set_env_variables': ('core.html#set_env_variables', 'bifrost_bridge/core.py'),
                                     'bifrost_bridge.core.show_project_env_vars': ( 'core.html#show_project_env_vars',
                                                                                    'bifrost_bridge/core.py')},
            'bifrost_bridge.hello_world': { 'bifrost_bridge.hello_world.cli': ('hello_world.html#cli', 'bifrost_bridge/hello_world.py'),
                                            'bifrost_bridge.hello_world.hello_two_world': ( 'hello_world.html#hello_two_world',
                                                                                            'bifrost_bridge/hello_world.py')}}}
