# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_bracken.ipynb.

# %% auto 0
__all__ = ['process_bracken_data', 'process_bracken_data_from_cli']

# %% ../nbs/06_bracken.ipynb 2
# That export there, it makes sure this code goes into the module.

# standard libs
import os
import re

# Common to template
# add into settings.ini, requirements, package name is python-dotenv, for conda build ensure `conda config --add channels conda-forge`
import dotenv  # for loading config from .env files, https://pypi.org/project/python-dotenv/
import envyaml  # Allows to loads env vars into a yaml file, https://github.com/thesimj/envyaml
import fastcore  # To add functionality related to nbdev development, https://github.com/fastai/fastcore/
from fastcore import (
    test,
)
from fastcore.script import (
    call_parse,
)  # for @call_parse, https://fastcore.fast.ai/script
import json  # for nicely printing json and yaml
from fastcore import test

#!export
from . import core

# %% ../nbs/06_bracken.ipynb 5
def process_bracken_data(
    input_path: str,
    output_path: str = "./output.tsv",
    replace_header: str = None,
    filter_columns: str = None,
    transpose: bool = True,
):
    """
    Process Bracken data.

    This function processes Bracken data files by importing the data, optionally replacing the header,
    transposing the data, filtering columns, and exporting the processed data to an output file.

    Arguments:
        input_path (str): Path to the input file.
        output_path (str): Path to the output file (default: './output.tsv').
        replace_header (str): Header to replace the existing header (default: None).
        filter_columns (str): Columns to filter from the header (default: None).
        transpose (bool): Whether to transpose the data (default: True).
    """

    df = core.DataFrame()
    df.import_data(input_path, file_type="tsv", add_header=False)

    # df.print_header()
    df.show()

    if replace_header:
        df.rename_header(replace_header)

    if filter_columns:
        df.filter_columns(filter_columns)

    # print(df.df)
    # print(type(df.df))

    # df.export_data(output_path, file_type='tsv')


@call_parse
def process_bracken_data_from_cli(
    input_path: str,
    output_path: str = "./output.tsv",
    replace_header: str = None,
    filter_columns: str = None,
):
    process_bracken_data(input_path, output_path, replace_header, filter_columns)
